# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test

  debian:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: bash test/resources/debian/pre_test
      - run: lein run -- test/resources/debian/tasks.clj
      - run: bash test/resources/debian/post_test

  mac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-v1-dependencies-{{ checksum "project.clj" }}
            - mac-v1-dependencies-
      - run:
          command: |
            sudo mkdir -p /usr/local/bin/
            sudo curl -sfLo /usr/local/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
            sudo chmod +x /usr/local/bin/lein
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: mac-v1-dependencies-{{ checksum "project.clj" }}

workflows:
    version: 2
    all_test:
      jobs:
        - build
        - debian
