name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-deps-${{ hashFiles('project.clj') }}
      - run: lein deps
      - run: make test
      - run: sudo make local_jar_test
