name: test
on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-deps-${{ hashFiles('project.clj') }}
      - run: lein deps
      - run: make test
      - run: sudo make local_jar_test

  darwin:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install leiningen
        run: brew install leiningen
      - run: lein deps
      - run: make test
      - run: make local_jar_test
